### ISSUE TITLE
Pot更新到3.0版本，原有插件需要更新，否则无法安装

### ISSUE THREAD

**Issue by TJNOV** [TechDecryptor/pot-app-translate-plugin-caiyun#2]
Pot更新到3.0版本，原有插件需要更新，否则无法安装

![图片](https://github.com/TechDecryptor/pot-app-translate-plugin-caiyun/assets/76683201/71dbacc9-8388-4106-99eb-3c3192658dd3)

**Comment by TechDecryptor** [comment]
https://github.com/TechDecryptor/pot-app-translate-plugin-caiyun/releases/tag/2.0.0
